### ISSUE TITLE
[Rule] no-default-prop -> checks if you are setting the prop to its default value

### ISSUE THREAD

**Issue by panstromek** [quasarframework/eslint-plugin-quasar#4]
Just an idea for a rule I had.

Code that is rejected.
```vue
<!--    'md' is the default value, therefore this setting is redundant  -->
<q-btn size="md" />

<!-- same here -->
<q-btn :dense="false" />
```

The only problem that I see with this is that I sometimes change the defaults programmaticaly like
```js
import { QInput } from 'quasar'

QInput.options.props.dark.default = true
```
Kinda dirty but does the job. I change the default so that I don't need to repeat it everywhere, but with this rule I'd need to disable it everytime I use the component, which makes it pointless.

Also, some defaults are set via functions, so they are impossible to check in general case.

**Comment by hawkeye64** [comment]
Also, some boolean props have default of true, so the `:prop="false"` would be needed

**Comment by hawkeye64** [comment]
Maybe if we come up with a list of redundant items, we can figure out how to implement the rule. For instance, checking for default value and comparing.

**Comment by panstromek** [comment]
One other complication is that now that we have dark mode, props can change its default value (I guess it's during build, so probably not detectable by external linter).

**Comment by hawkeye64** [comment]
That is correct

**Comment by hawkeye64** [comment]
closing for age
