### ISSUE TITLE
[Rule] no-exclusive-prop-conflicts for exclusive props (eg. filled, standout)

### ISSUE THREAD

**Issue by panstromek** [quasarframework/eslint-plugin-quasar#5]
Some components have have excluding props, ie. only one of them can be used. Eg.

```vue
<!-- wrong: filled and standout can't be used together -->
<q-input filled standout />
```

**Comment by hawkeye64** [comment]
can you help me get a list together of these exclusive props?

**Comment by panstromek** [comment]
I don't think I know all of them but let's start somewhere. Here are the ones I recall now.

 - QInput, QSelect, QField 
   - filled, outlined, standout, borderless
   - square, rounded

- QBtn
   - flat, push, outline
   - round, rounded

**Comment by hawkeye64** [comment]
Good ones. I think we'll have to ask Razvan or PDan to help out on this.

**Comment by panstromek** [comment]
I think another one would be `true-value` and `val` for checkbox, I think? (seems like `true-value` doesn't do anything when the model is an array)

**Comment by hawkeye64** [comment]
Oh, good one. :heart: Wish we could collect a few more before making a release.

**Comment by hawkeye64** [comment]
closing for age
