### ISSUE TITLE
[Rule] required-with-prop - missing prop that is required with some other prop

### ISSUE THREAD

**Issue by panstromek** [quasarframework/eslint-plugin-quasar#6]
Similar to the previous proposal for catching conflicting props, this one would report if you miss prop that is required only with other one you already use. 

There are only few of those cases, the only one I recall now is `filter` and `filter-method` from QTable, but that one is also a bit more complicated because it is required only if the value is an Object, so generally not detectable by linter.

> filter: When using an Object it requires 'filter-method' to also be specified since it will be a custom filtering

But if there are some other ones, it might be cool rule to have.

**Comment by hawkeye64** [comment]
`error` and `error-message` would be another for QField, QSelect and QInput

**Comment by hawkeye64** [comment]
closing for age
